#!/bin/sh
for i in `ls -d */CVS`;
do
	# remove "/CVS" part of string i
	i=${i%/CVS}
	echo $i:
	cd $i
	cvs update -d -P
	cd ..
done

for i in `ls -d */.rsync`;
do
	remote=`cat $i` # note: must end with a slash
	# remove "/.rsync" part of string i
	i=${i%/.rsync}
	echo $i:
    rsync -avz $remote $i
done

for i in `ls -d */.svn`;
do
	# remove "/.svn" part of string i
	i=${i%/.svn}
	echo $i:
	cd $i
	svn update --ignore-externals
	cd ..
done

for i in `ls -d */.git`;
do
	# remove "/.git" part of string i
	i=${i%/.git}
	echo $i:
	cd $i
	git fetch --all
	if grep svn-remote .git/config > /dev/null; then
		git svn fetch --all
	fi
	cd ..
done

for i in `ls -d */.hg`;
do
	# remove "/.hg" part of string i
	i=${i%/.hg}
	echo $i:
	cd $i
	hg pull
	cd ..
done
